#!/usr/bin/env zsh

local plugin_basedir="${_create_zsh_plugin_basedir:h}"

if (( $+functions[zpm] )); then
  echo zpm detected, this is awesome!!!
  is_zpm=true
fi

if [[ -z "$1" ]]; then
  echo 'Usage: create-zsh-plugin plugin-name'
  return -1
fi

plugin_name="$1"

mkdir -p "${plugin_name}"
echo -n >! "${plugin_name}/${plugin_name}.plugin.zsh"

cat "${plugin_basedir}/templates/zero.zsh" >> "${plugin_name}/${plugin_name}.plugin.zsh"

echo 'Your plugin will contain completions or autoloadable functions? Yes/No'
select yn in "Yes" "No"; do
  case $yn in
    Yes)
      cat "${plugin_basedir}/templates/fpath.zsh" >> "${plugin_name}/${plugin_name}.plugin.zsh"
      mkdir -p "${plugin_name}/functions"
      break;;
    No ) true;;
  esac
done

echo 'Your plugin will contain binaries? Yes/No'
select yn in "Yes" "No"; do
  case $yn in
    Yes)
      cat "${plugin_basedir}/templates/path.zsh" >> "${plugin_name}/${plugin_name}.plugin.zsh"
      mkdir -p "${plugin_name}/bin"
      break;;
    No ) true;;
  esac
done

echo 'Add hello world template? Yes/No'
select yn in "Yes" "No"; do
  case $yn in
    Yes)
      cat "${plugin_basedir}/templates/hello.zsh" >> "${plugin_name}/${plugin_name}.plugin.zsh"
      break;;
    No ) true;;
  esac
done

if (( $+functions[zpm-link] )); then
  echo 'Install this plugin via zpm link? Yes/No'
  select yn in "Yes" "No"; do
    case $yn in
      Yes)
        zpm link "${plugin_name}"
        break;;
      No ) true;;
    esac
  done
fi
